[versions]
agp = "8.5.1"
kotlin = "1.9.0"
junit = "4.13.2"
dokka = "1.9.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }